version: '3.6'

services:
  php:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: zeus-php
    depends_on:
      - database
    networks:
      - backend-network

  database:
    image: 'mariadb:10.5'
    container_name: zeus-database
    restart: 'on-failure'
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge