apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dolibarr
  name: dolibarr
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dolibarr
  template:
    metadata:
      labels:
        app: dolibarr
      name: dolibarr
    spec:
      containers:
        - image: ghcr.io/adjikpo/Zeus:latest
          imagePullPolicy: "Always"
          name: dolibarr
          ports:
            - containerPort: 80
              protocol: TCP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/www/dolibarr/htdocs/conf
              name: dolibarr-config
          env:
            - name: DOLIBARR_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: dolibarr-credentials
                  key: DOLIBARR_DB_NAME
            - name: DOLIBARR_DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: dolibarr-credentials
                  key: DOLIBARR_DB_USERNAME
            - name: DOLIBARR_DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: dolibarr-credentials
                  key: DOLIBARR_DB_PASSWORD
            - name: DOLIBARR_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: dolibarr-credentials
                  key: DOLIBARR_DB_HOST
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      nodeName: minikube
      preemptionPolicy: PreemptLowerPriority
      priority: 0
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      tolerations:
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
          tolerationSeconds: 300
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
          tolerationSeconds: 300
      volumes:
        - name: dolibarr-config
          persistentVolumeClaim:
            claimName: dolibarr-config