apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: dolibarr-db-data
  name: dolibarr-db-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi