apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: dolibarr-config
  name: dolibarr-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi